### ISSUE TITLE
https://github.com/tomykaira/clockwork is dead

### ISSUE THREAD

**Issue by anhkind** [Rykian/clockwork#1]
Hi,

https://github.com/tomykaira/clockwork is dead at the moment. I want to know if we users still have the support of the gem from this repository.

Thanks.

**Comment by Rykian** [comment]
Yup,

I'm doing minimal maintainance here on this repo, no new features planned for the moment but PR are opened.
I've just fixed a problem with shutdown signal by taking a commit on another repos for the moment (https://github.com/Rykian/clockwork/releases/tag/v2.0.1)

**Comment by anhkind** [comment]
Great to hear that. One question, are you taking the ownership of the gem on `rubygems` https://rubygems.org/gems/clockwork as well? Will it be updated with the codes from this repository?

**Comment by Rykian** [comment]
Sorry for the late answer, I've asked for it, I'm waiting for it now!

--
Thibault Lacroux
Développeur web/DevOps Freelance
Mobile : 06 83 50 57 45
5, Rue Sainte-Catherine
53000 Laval

**Comment by Rykian** [comment]
It's updated on Rubygems.org thanks to @blackjid !
