### ISSUE TITLE
Callbacks for shutdown

### ISSUE THREAD

**Issue by nasa42** [Rykian/clockwork#30]
We need to deregister some external services when an instance of Clockwork goes down gracefully. It would be great if Clockwork can support callbacks for `shutdown` and/or `graceful_shutdown`.
I can open a PR if this feature is ok to be accepted.

**Comment by phoffer** [comment]
I'm currently doing this in a project, which seems to work well enough. However, I'm still in dev and haven't deployed anywhere, so I'm unsure if the behavior would change.

```ruby
module Clockwork
  every(60, 'some.task') { puts 'hello' }
  at_exit do
    puts 'goodbye'
  end
end
```

**Comment by nasa42** [comment]
Closing in favour of `at_exit`. Thanks @phoffer!
