### ISSUE TITLE
Mention active_support/time in README.

### ISSUE THREAD

**Issue by kenn** [Rykian/clockwork#40]
**Breaking change**: clockwork stopped working after updating from 2.0.2 to 2.0.3 due to `3.minutes` getting NoMethodError, and it turned out, this change caused the issue.

https://github.com/Rykian/clockwork/commit/7418d24026ab4bcad3cd3a19d46d45c61275ac68

I've fixed the issue by adding back 'active_support/time'.

```ruby
require 'clockwork'
require 'active_support/time'
```

As we have config examples with `3.minutes` or `1.hour` in README, I believe we should also have `require 'active_support/time'` in the examples as well.

**Comment by Rykian** [comment]
Thanks for the report, it's updated!

**Comment by javierjulio** [comment]
Thanks @kenn for this! Why was this just a documentation change @Rykian? I'm disappointed that 7418d24 went out disguised as a patch release as it did cause breakage for Rails apps despite its intention not too. In fact the test in c055d0c clearly gives it away as it had to include `active_support/time` just for them to pass. That should have been a red flag. @Rykian I can help contribute. Would you be open to:
- a PR for reverting commit 7418d24 and releasing as 2.0.4?
- maybe consider removing the 2.0.3 release?
- re-introduce commit 7418d24 for a 3.0 major release? I would suggest having better tests too for when that commit is reintroduced too. I'm not sure if the change is sufficient to handle timezone correctly.
- also have a changelog or do you prefer to have changes listed in GitHub releases?

**Comment by pboling** [comment]
> maybe consider pulling down the 2.0.3 release?

The workaround is not egregious, and many people probably don't even notice the bug, having already loaded the library.  Yanking is an earthquake.  This is simply a bug like any other, calling for a new patch.

**Comment by javierjulio** [comment]
@pboling I agree, I think a patch is sufficient. Keep in mind people won't notice because its a silent failure which isn't good.

@Rykian would you be open to it? I can work on that and have it ready for you.

**Comment by Rykian** [comment]
Yep, I’m open to a patch.

Thank you in advance ;)



—
Thibault Lacroux
Développeur web/DevOps Freelance
Mobile : 06 83 50 57 45
5, Rue Ste Catherine
53000 Laval

On 28 February 2018 at 14:49:21, Javier Julio (notifications@github.com) wrote:

@pboling I agree, I think a patch is sufficient. Keep in mind people won't notice because its a silent failure which isn't good.

@Rykian would you be open to it? I can work on that and have it ready for you.

**Comment by javierjulio** [comment]
@Rykian great thanks! I've set aside time tomorrow so I'll work on it then and have it ready for you. I'll make some suggestions too for those that would like to remove the dependency whether as a 3.0 or a 2.x release. I think it could be removed earlier if the library makes it an optional dependency.
