### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by MaicolBen** [Rykian/clockwork#5]
On my server, the amount of memory is almost proportional to the amount of tasks, I've 21 tasks, and it consumes 90% of the memory (8 GB), if I remove 2-3 tasks, the memory used decreases to 82% and so on. I guess it is the same issue that https://github.com/adamwiggins/clockwork/issues/17

**Comment by gr8bit** [comment]
I'm curious: do you let clockwork do the work or do you use background runners like ActiveJob, Sidekiq etc.?

**Comment by MaicolBen** [comment]
Yes, I let clockwork do the job, but I switched to whenever and the memory decreased.

I know that the best is to send to background everything. I'll close this issue since it seems to depend on the code that you're running and not in clockwork.
