### ISSUE TITLE
Release 2.0.4

### ISSUE THREAD

**Issue by thomasfedb** [Rykian/clockwork#52]
Version 2.0.3 has some breaking changes from 2.0.2 which appear to have been resolved in the master branch, is a release possible soonish?

**Comment by DianeLooney** [comment]
Bumping this in hopes that we can get a release. Has caused at-least 3 headaches on my team.

**Comment by thomasfedb** [comment]
@Rykian do you consider this fork to be maintained?

**Comment by 9mm** [comment]
what were the breaking changes?

**Comment by thomasfedb** [comment]
@9mm https://github.com/Rykian/clockwork/commit/1767c6ba909cf341583c372f0a2954c949fe0563

**Comment by DianeLooney** [comment]
I think we can close this issue now, @Rykian . Thanks for the revert.
